spring:
  datasource:
    # 驱动配置信息
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://teriri.com:3306/hodts_db?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&autoReconnect=true&failOverReadOnly=false
    username: olddrivers
    password: 123456
    # 连接池配置信息
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    ### 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#  main:
#    allow-bean-definition-overriding: true

  # redis config
  redis:
    database: 0
    # Redis服务器地址
    host: teriri.com
    # Redis服务器端口
    port: 6379
    # Redis服务器连接密码
    password: harunasan
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        #连接池最大连接数
        max-active: 8
        # 连接池最大阻塞等待时间
        max-wait: -1
    # 连接超时时间（毫秒）
    timeout: 1000

# druid监控页面账号
druid:
  admin:
    druidUsername: druid_admin
    druidPassword: 123456

#logging:
#  path: log/druid

server:
  port: 8000

jwt:
  # 存放Token的Header Key
  header: Authorization
  #jwt的秘钥key "Harunasan" SHA256
  secret: 3f3a6639098c6afc5055260a411c283e3990e58424efd3be42a70c089c7dae98
  #token有效时间（毫秒）
  expiration: 604800000
  route:
    login: /auth/login    #登录地址
    refresh: /auth/refresh  #刷新token地址
    register: /auth/register  #注册的地址

# OSS 相关参数
oss:
  ossEndpoint: https://oss-cn-shenzhen.aliyuncs.com
  ossAccessId: LTAIKF2nFJq1tfp8
  ossAccessKey: 2w1aeb21vzgtHb5wBD6V2YOWX9djXD
  bucket: hsdts

# mybatis 相关参数
mybatis:
  # Mapper.xml所在的位置
  mapper-locations: classpath:mapping/*.xml
  # entity扫描的包名
  type-aliases-package: com.cqnu.harunasandrivingtestingsystem.entity


# pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  params: count=countSql
  support-methods-arguments: true
